export const caseStudies = {
  'student-gpt': {
    title: 'Student GPT - An Academic AI Assistant',
    tags: [['Figma','green'],['UI Design','blue'],['Mobile App','red']],
    heroImg: 'https://www.figma.com/api/mcp/asset/5f5541cf-c2e5-4e88-89ab-f711906dddfb',
    timeline: '2 Months',
    role: 'UIUX Designer',
    outcome: 'High-fidelity prototype',
    overview: `Student GPT is an AI-driven tool designed to help students engage with their course materials in a more effective and efficient manner. By allowing users to upload subject-related documents such as PDFs, lecture notes, and slides, the system generates accurate, contextual responses based on the content of the uploaded materials and user prompts. It ensures that every response is deeply rooted in the course content, making academic help more reliable and targeted.`,
    vision: 'Crafting a Seamless interaction between technical architecture and user experience',
    strategy: 'Prioritizing Aesthetic precision to ensure the solution remains visually timeless.',
    problem: 'Students often struggle to quickly find specific answers or contextual explanations within dense academic materials like textbooks, lecture slides, and research papers. Traditional search methods are inefficient and lack contextual understanding, leading to wasted time and cognitive overload.',
    solution: 'Student GPT provides an AI-powered academic assistant that allows users to upload their specific course materials. It uses natural language processing to understand queries and provides precise, context-aware answers directly sourced from the uploaded documents, complete with citations and explanations.',
    designProcess: [
      { phase: 'Discover', activities: ['User Interviews', 'Surveys', 'Competitive Analysis'] },
      { phase: 'Define', activities: ['User Personas', 'Empathy Mapping', 'Problem Statement'] },
      { phase: 'Ideate', activities: ['User Flow', 'Information Architecture', 'Wireframing'] },
      { phase: 'Design', activities: ['UI Design', 'Prototyping', 'Usability Testing'] }
    ],
    competitiveAnalysis: [
      { name: 'ChatGPT', strength: 'Versatile and conversational.', weakness: 'Hallucinates, lacks specific context of the student\'s exact course material without constant prompting.' },
      { name: 'Chegg/CourseHero', strength: 'Large database of past questions.', weakness: 'Expensive, often promotes academic dishonesty rather than actual learning.' },
      { name: 'Ctrl+F (Standard Search)', strength: 'Fast and ubiquitous.', weakness: 'Only finds exact keyword matches, cannot explain concepts or summarize.' }
    ],
    userPersona: {
      name: 'Alex Chen',
      role: 'Computer Science Undergraduate',
      bio: 'Alex is juggling multiple heavy-reading courses. He wants to understand core concepts quickly without reading 50-page PDFs front-to-back every time he needs to clarify a minor point for his assignments.',
      goals: ['Save time studying', 'Understand complex topics easily', 'Get reliable answers based on his syllabus'],
      frustrations: ['Generic AI gives wrong answers', 'Finding information in long PDFs is tedious', 'Feeling overwhelmed by the sheer volume of reading']
    },
    empathyMap: {
      says: ['"Where was that formula mentioned in the slides?"', '"I wish I had a tutor available at 2 AM."'],
      thinks: ['"I don\'t have time to re-read this whole chapter."', '"Is this AI giving me accurate info for my specific class?"'],
      does: ['Uses multiple tabs for research', 'Skims through documents looking for bold text', 'Asks classmates for summaries'],
      feels: ['Overwhelmed by deadlines', 'Frustrated by inefficient study methods', 'Anxious about exams']
    },
    howItWorks: [
      { bold: 'Upload Content', text: ': Users upload their course-related documents (e.g., lecture slides, notes, PDFs).' },
      { bold: 'AI Processing', text: ': The system scans and processes the uploaded materials, extracting key concepts, terminology, and context specific to the subject.' },
      { bold: 'Contextual Responses', text: ': Users can ask questions or seek clarifications related to the uploaded content. Student GPT generates accurate, in-depth responses that reflect the exact context from the documents.' },
      { bold: 'Learning Aid', text: ': It aids students in quick clarifications or deeper explorations of complex topics, providing relevant answers derived from the uploaded documents.' },
    ],
    keyBenefits: [
      { bold: 'Quick Clarifications', text: ': Get answers to specific questions based on the course content.' },
      { bold: 'Deeper Understanding', text: ': Dive deeper into subjects with responses that integrate the full context of the material.' },
      { bold: 'Time-Saving', text: ': Streamline the academic workflow by having an AI assistant that understands the material, reducing the need for manual searching or external help.' },
      { bold: 'Target Audience', text: ': Students, educators, and anyone seeking an AI-driven tool to improve their interaction with course materials.' },
    ],
    projectLink: 'https://www.behance.net/gallery/223935725/Student-GPT-Your-Smart-Academic-Assistant',
    pdfUrl: '/src/slides/slides/OE-Reliability-Block-Diagram.pdf',
    nextColor: 'pink',
  },
  'project-collab': {
    title: 'Project Collab',
    tags: [['Figma','blue'],['UI Design','pink'],['Mobile App','light-orange']],
    heroImg: 'https://www.figma.com/api/mcp/asset/e534b0e9-ae92-4bef-b2f9-59cd22c4a185',
    timeline: '3 Months',
    role: 'UIUX Designer',
    outcome: 'Mobile UI System',
    overview: 'A Platform designed to connect innovators and students for collaborative projects, featured a sleek and intuitive mobile interface. The app enables seamless collaboration and idea sharing between project seekers and contributors.',
    vision: 'Creating a unified collaboration space that bridges the gap between ideas and execution.',
    strategy: 'Designing intuitive user flows that reduce friction in the collaboration process.',
    howItWorks: [
      { bold: 'Discover Projects', text: ': Browse through projects posted by innovators seeking collaborators.' },
      { bold: 'Connect', text: ': Apply to join projects or post your own with a simple form flow.' },
      { bold: 'Collaborate', text: ': Use built-in tools to communicate and track project progress.' },
      { bold: 'Deliver', text: ': Share outcomes and build your collaborative portfolio.' },
    ],
    keyBenefits: [
      { bold: 'Easy Discovery', text: ': Find relevant projects quickly with smart filtering.' },
      { bold: 'Streamlined Onboarding', text: ': Get started collaborating in minutes.' },
      { bold: 'Built-in Tools', text: ': Everything you need without leaving the app.' },
      { bold: 'Portfolio Building', text: ': Showcase your collaborative work history.' },
    ],
    projectLink: 'https://www.figma.com',
    nextColor: 'orange',
  },
  'agrivision': {
    title: 'AgriVision - Advanced Horticulture for enhanced crop Production',
    tags: [['React Native','purple'],['Machine Learning','light-orange'],['IoT','green']],
    heroImg: 'https://www.figma.com/api/mcp/asset/613a7a57-f382-4289-88c7-535cc6814423',
    timeline: '4 Months',
    role: 'Full Stack Developer',
    outcome: 'Production App',
    overview: 'An Innovative IoT and Machine Learning project focused on enhancing crop production using React Native for the mobile application. The system integrates real-time sensor data with ML predictions to optimise agricultural yields.',
    vision: 'Empowering farmers with data-driven insights to maximise their harvest potential.',
    strategy: 'Combining IoT sensor networks with ML models to deliver actionable recommendations.',
    howItWorks: [
      { bold: 'Sensor Network', text: ': IoT devices collect real-time soil, temperature, and humidity data.' },
      { bold: 'ML Analysis', text: ': Machine learning models process sensor data to predict optimal conditions.' },
      { bold: 'Mobile Dashboard', text: ': Farmers view insights and alerts via the React Native app.' },
      { bold: 'Automated Actions', text: ': Systems trigger irrigation and nutrient delivery automatically.' },
    ],
    keyBenefits: [
      { bold: 'Real-time Monitoring', text: ': Always-on visibility into crop conditions.' },
      { bold: 'Predictive Insights', text: ': Get ahead of problems before they impact yield.' },
      { bold: 'Automation', text: ': Reduce manual intervention with smart triggers.' },
      { bold: 'Yield Improvement', text: ': Measured increases in crop output and quality.' },
    ],
    projectLink: 'https://github.com',
    nextColor: 'blue',
  },
  'chronicles': {
    title: 'Containerized Chronicles - A Authenticated Blogging platform',
    tags: [['Django','pink'],['Web App','orange'],['Blog Site','bg']],
    heroImg: 'https://www.figma.com/api/mcp/asset/aaebe876-dec6-429a-af9c-f787b6fb58c1',
    timeline: '3 Months',
    role: 'Full Stack Developer',
    outcome: 'Deployed Web App',
    overview: 'A Full-stack Django-based blogging platform with secure authentication, allowing users to create, edit, and share their stories in a containerized environment using Docker for reliable deployment.',
    vision: 'Building a secure and scalable blogging platform that anyone can self-host effortlessly.',
    strategy: 'Leveraging Django\'s auth system with Docker containerization for easy and reliable deployment.',
    howItWorks: [
      { bold: 'Authentication', text: ': Secure sign-up and login with Django\'s built-in auth framework.' },
      { bold: 'Content Creation', text: ': Rich text editor for writing and formatting blog posts.' },
      { bold: 'Containerization', text: ': Docker ensures consistent deployment across environments.' },
      { bold: 'Scalability', text: ': Built to handle growing user bases and content volumes.' },
    ],
    keyBenefits: [
      { bold: 'Security First', text: ': Robust authentication protects user content.' },
      { bold: 'Easy Deployment', text: ': Docker makes hosting simple and reliable.' },
      { bold: 'Rich Content', text: ': Full-featured editor for engaging blog posts.' },
      { bold: 'Scalable Architecture', text: ': Grows with your audience and content needs.' },
    ],
    projectLink: 'https://github.com',
    nextColor: 'green',
  },
  'tripweaver': {
    title: 'TripWeaver - A Tour guide web app',
    tags: [['Figma','green'],['UI Design','blue'],['Web App','light-orange']],
    heroImg: 'https://www.figma.com/api/mcp/asset/7b59616b-8983-4866-8e2c-8a2a590207a5',
    timeline: '2 Months',
    role: 'UIUX Designer',
    outcome: 'Web UI Design',
    overview: 'A Web based tour plan guide that offers personalized recommendations and user-friendly interface for travellers. The platform helps users discover destinations, plan itineraries, and book experiences seamlessly.',
    vision: 'Making travel planning effortless and personalized for every journey.',
    strategy: 'Creating an intuitive web interface that guides users through their travel planning process.',
    howItWorks: [
      { bold: 'Destination Discovery', text: ': Explore destinations with personalized recommendations.' },
      { bold: 'Itinerary Planning', text: ': Build custom travel plans with drag-and-drop simplicity.' },
      { bold: 'Experience Booking', text: ': Book tours, activities, and accommodations in one place.' },
      { bold: 'Travel Companion', text: ': Get real-time updates and local insights during your trip.' },
    ],
    keyBenefits: [
      { bold: 'Personalized', text: ': Recommendations tailored to your preferences.' },
      { bold: 'Comprehensive', text: ': Everything you need in one platform.' },
      { bold: 'User-Friendly', text: ': Intuitive design makes planning easy.' },
      { bold: 'Real-Time', text: ': Stay updated with live travel information.' },
    ],
    projectLink: 'https://www.behance.net',
    nextColor: 'purple',
  },
};